"""Third migration

Revision ID: 0c0fd312a11d
Revises: 14413faba71c
Create Date: 2024-02-27 15:24:25.120690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0fd312a11d'
down_revision: Union[str, None] = '14413faba71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('main_image_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('single_image_id', sa.Integer(), nullable=True))
    op.drop_column('articles', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'single_image_id')
    op.drop_column('articles', 'main_image_id')
    # ### end Alembic commands ###
